export const CONNECT_MENTOR_START = "CONNECT_MENTOR_START";
export const CONNECT_MENTOR_SUCCESS = "CONNECT_MENTOR_SUCCESS";
export const CONNECT_MENTOR_FAIL = "CONNECT_MENTOR_FAIL";

export const ADD_MESSAGE_INTO_LIST = "ADD_MESSAGE_INTO_LIST";

export const GET_ROOMS_START = "GET_ROOMS_START";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_ROOMS_FAIL = "GET_ROOMS_FAIL";
