export const CONNECT_MENTOR_START = "CONNECT_MENTOR_START";
export const CONNECT_MENTOR_SUCCESS = "CONNECT_MENTOR_SUCCESS";
export const CONNECT_MENTOR_FAIL = "CONNECT_MENTOR_FAIL";

export const ADD_MESSAGE_INTO_LIST = "ADD_MESSAGE_INTO_LIST";
