export const GET_MENTORS_LIST_START = "GET_MENTORS_LIST_START";
export const GET_MENTORS_LIST_SUCCESS = "GET_MENTORS_LIST_SUCCESS";
export const GET_MENTORS_LIST_FAILURE = "GET_MENTORS_LIST_FAILURE";

export const GET_ONE_MENTOR_START = "GET_ONE_MENTOR_START";
export const GET_ONE_MENTOR_SUCCESS = "GET_ONE_MENTOR_SUCCESS";
export const GET_ONE_MENTOR_FAILURE = "GET_ONE_MENTOR_FAILURE";
