export const FETCH_TUTORIALS_START = "FETCH_TUTORIALS_START";
export const FETCH_TUTORIALS_SUCCESS = "FETCH_TUTORIALS_SUCCESS";
export const FETCH_TUTORIALS_FAILURE = "FETCH_TUTORIALS_FAILURE";

export const FETCH_ONE_TUTORIAL_START = "FETCH_ONE_TUTORIAL_START";
export const FETCH_ONE_TUTORIAL_SUCCESS = "FETCH_ONE_TUTORIAL_SUCCESS";
export const FETCH_ONE_TUTORIAL_FAILURE = "FETCH_ONE_TUTORIAL_FAILURE";

export const CLEAR_TUTORIAL = "CLEAR_TUTORIAL";
export const CLEAR_ERRORS_AND_LINK = "CLEAR_ERRORS_AND_LINK";

export const GET_SAVED_TUTORIALS_START = "GET_SAVED_TUTORIALS_START";
export const GET_SAVED_TUTORIALS_SUCCESS = "GET_SAVED_TUTORIALS_SUCCESS";
export const GET_SAVED_TUTORIALS_FAILURE = "GET_SAVED_TUTORIALS_FAILURE";

export const SEARCH_TUTORIALS_START = "SEARCH_TUTORIALS_START";
export const SEARCH_TUTORIALS_SUCCESS = "SEARCH_TUTORIALS_SUCCESS";
export const SEARCH_TUTORIALS_FAILURE = "SEARCH_TUTORIALS_FAILURE";
